### PR TITLE
License the code as MIT

### PR DESCRIPTION
**Pull request by navarr**
Right now gmailactions is licensed as "Commercial."  This pull request is a proposal to license the work under the MIT license (free for all!)

In order to officially do so, you technically need permission from all "license" holders - as there was no assignment of code ownership during PR process:
- [x] @navarr
- [x] @punkstar
- [x] @rbrown 
- [x] @ashsmith 

---

To start us off: I hereby grant permission to license the code I've written under the MIT license.

### CODE REVIEW

**Comment by punkstar** [comment]
:+1: This was mistakenly published without a license and "Commercial" added to the composer.json by @rbrown presumably because there was not one present.  The @meanbee extensions on Github are not commercial have historically be published under OSL, but most recent repository are released under MIT.

I acknowledge and appreciate your work @navarr on this extension and support explicitly specifying an open license!

**Comment by rbrown** [comment]
I hereby grant permission to license the code I've written under the MIT license.

Sorry about that!

**Comment by punkstar** [comment]
@rbrown It really wasn't your fault. :)

**Comment by ashsmith** [comment]
Yep, I'm happy for the licence change!

**Comment by punkstar** [comment]
#efficiency

**Pull request merged**
